# Build settings
markdown: kramdown
theme: minima

title: VEBER Arnaud
tagline: VEBERArnaud's Blog
description: Dev, Ops & Shits
baseurl: /
url: http://blog.veber.io

author:
    name: VEBER Arnaud
    email: arnaud@veber.pw
    url: https://twitter.com/VEBERArnaud

paginate: 1

github:
    repo: https://github.com/VEBERArnaud/blog.veber.io
